# Generated by Django 5.0.3 on 2024-03-23 09:49

import app.domain.entities.time_report
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("time_report", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timereport",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "pending"),
                    ("APPROVED", "approved"),
                    ("REJECTED", "rejected"),
                ],
                default=app.domain.entities.time_report.TimeReportStatus["PENDING"],
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="timereport",
            name="type",
            field=models.CharField(
                choices=[("IN", "in"), ("OUT", "out")], max_length=20
            ),
        ),
    ]
